---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - rolebindings
  - roles
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - product.webshop.harikube.info
  resources:
  - emails
  - licences
  - orders
  - payments
  - registrationrequests
  - registrytokens
  - tenants
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - product.webshop.harikube.info
  resources:
  - emails/finalizers
  - licences/finalizers
  - orders/finalizers
  - payments/finalizers
  - registrationrequests/finalizers
  - registrytokens/finalizers
  - tenants/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - product.webshop.harikube.info
  resources:
  - emails/status
  - licences/status
  - orders/status
  - payments/status
  - registrationrequests/status
  - registrytokens/status
  - tenants/status
  - users/status
  verbs:
  - get
  - patch
  - update
