apiVersion: v1
kind: Secret
metadata:
  name: user-sample-password
type: Opaque
stringData:
  password: supersecret123
---
apiVersion: product.webshop.harikube.info/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: example-webshop-service
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # REQUIRED fields
  passwordRef: user-sample-password
  firstName: John
  lastName: D'oe-Smith
  email: john.doe@example.com
  country: USA
  city: New York
  address: 123 Main St, Apt 4B
  postalCode: '10001'
  
  # OPTIONAL fields
  companyName: Tech Innovators Inc. 
  taxNumber: ABC-123456789
  phoneNumber: "+15551234567"
