---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: payments.product.webshop.harikube.info
spec:
  group: product.webshop.harikube.info
  names:
    kind: Payment
    listKind: PaymentList
    plural: payments
    singular: payment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.price
      name: Price
      type: number
    - jsonPath: .status.paymentTimestamp
      name: Date
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Payment is the Schema for the payments API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PaymentSpec defines the desired state of Payment.
            properties:
              price:
                description: Price represents the price of the payment in cents.
                format: int64
                type: integer
            required:
            - price
            type: object
          status:
            description: PaymentStatus defines the observed state of Payment.
            properties:
              errorMessage:
                type: string
              errorTimestamp:
                format: date-time
                type: string
              lastGeneration:
                format: int64
                type: integer
              paymentTimestamp:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
