---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: products.product.webshop.harikube.info
spec:
  group: product.webshop.harikube.info
  names:
    kind: Product
    listKind: ProductList
    plural: products
    singular: product
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      type: string
    - jsonPath: .spec.price
      name: Price
      type: number
    name: v1
    schema:
      openAPIV3Schema:
        description: Product is the Schema for the products API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ProductSpec defines the desired state of Product.
            properties:
              addons:
                description: Addons represents a list of addons associated with the
                  product.
                items:
                  description: Addon is the Schema for the addons API.
                  properties:
                    apiVersion:
                      description: |-
                        APIVersion defines the versioned schema of this representation of an object.
                        Servers should convert recognized schemas to the latest internal value, and
                        may reject unrecognized values.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                      type: string
                    kind:
                      description: |-
                        Kind is a string value representing the REST resource this object represents.
                        Servers may infer this from the endpoint the client submits requests to.
                        Cannot be updated.
                        In CamelCase.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                      type: string
                    metadata:
                      type: object
                    spec:
                      description: AddonSpec defines the desired state of Addon.
                      properties:
                        addonType:
                          description: AddonType represents the type of the addon.
                          enum:
                          - product
                          - service
                          - support
                          - onetime
                          type: string
                        description:
                          description: Description represents a brief description
                            of the addon.
                          type: string
                        displayName:
                          description: DisplayName represents the human friendly name
                            of the addon.
                          type: string
                        price:
                          description: Price represents the price of the addon in
                            cents.
                          format: int64
                          type: integer
                      required:
                      - addonType
                      - displayName
                      - price
                      type: object
                    status:
                      description: AddonStatus defines the observed state of Addon.
                      properties:
                        lastGeneration:
                          format: int64
                          type: integer
                      type: object
                  type: object
                type: array
              description:
                description: Description represents a brief description of the addon.
                type: string
              displayName:
                description: DisplayName represents the human friendly name of the
                  addon.
                type: string
              price:
                description: Price represents the price of the product in cents.
                format: int64
                type: integer
            required:
            - displayName
            - price
            type: object
          status:
            description: ProductStatus defines the observed state of Product.
            properties:
              lastGeneration:
                format: int64
                type: integer
            type: object
        type: object
    selectableFields:
    - jsonPath: .spec.displayName
    served: true
    storage: true
    subresources:
      status: {}
