---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: licences.product.webshop.harikube.info
spec:
  group: product.webshop.harikube.info
  names:
    kind: Licence
    listKind: LicenceList
    plural: licences
    singular: licence
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      type: string
    - jsonPath: .spec.expireTimestamp
      name: Expire
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Licence is the Schema for the licences API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: LicenceSpec defines the desired state of Licence.
            properties:
              addons:
                description: Addons represents the list of addons associated with
                  this licence.
                items:
                  description: Addon is the Schema for the addons API.
                  properties:
                    apiVersion:
                      description: |-
                        APIVersion defines the versioned schema of this representation of an object.
                        Servers should convert recognized schemas to the latest internal value, and
                        may reject unrecognized values.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                      type: string
                    kind:
                      description: |-
                        Kind is a string value representing the REST resource this object represents.
                        Servers may infer this from the endpoint the client submits requests to.
                        Cannot be updated.
                        In CamelCase.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                      type: string
                    metadata:
                      type: object
                    spec:
                      description: AddonSpec defines the desired state of Addon.
                      properties:
                        addonType:
                          description: AddonType represents the type of the addon.
                          enum:
                          - product
                          - service
                          - support
                          - onetime
                          type: string
                        description:
                          description: Description represents a brief description
                            of the addon.
                          type: string
                        displayName:
                          description: DisplayName represents the human friendly name
                            of the addon.
                          type: string
                        price:
                          description: Price represents the price of the addon in
                            cents.
                          format: int64
                          type: integer
                      required:
                      - addonType
                      - displayName
                      - price
                      type: object
                    status:
                      description: AddonStatus defines the observed state of Addon.
                      properties:
                        lastGeneration:
                          format: int64
                          type: integer
                      type: object
                  type: object
                type: array
              description:
                description: Description represents a brief description of the licence.
                type: string
              displayName:
                description: DisplayName represents the human friendly name of the
                  licence.
                type: string
              expireTimestamp:
                description: ExpireTimestamp represents the expiration date of the
                  licence.
                format: date-time
                type: string
            required:
            - displayName
            - expireTimestamp
            type: object
          status:
            description: LicenceStatus defines the observed state of Licence.
            properties:
              errorMessage:
                type: string
              errorTimestamp:
                format: date-time
                type: string
              lastGeneration:
                format: int64
                type: integer
              licenceKey:
                description: |-
                  LocalObjectReference contains enough information to let you locate the
                  referenced object inside the same namespace.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
            type: object
        type: object
    selectableFields:
    - jsonPath: .spec.displayName
    served: true
    storage: true
    subresources:
      status: {}
