---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: emails.product.webshop.harikube.info
spec:
  group: product.webshop.harikube.info
  names:
    kind: Email
    listKind: EmailList
    plural: emails
    singular: email
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.toAddress
      name: Email
      type: string
    - jsonPath: .status.sentTimestamp
      name: Sent
      type: date
    - jsonPath: .status.errorMessage
      name: Error
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Email is the Schema for the emails API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: EmailSpec defines the desired state of Email.
            properties:
              body:
                description: Body represents the body content of the email.
                type: string
              fromAddress:
                description: FromAddress represents the email address of the sender.
                type: string
              fromName:
                description: FromName represents the name of the sender.
                type: string
              subject:
                description: Subject represents the subject of the email.
                type: string
              toAddress:
                description: FromAddress represents the email address of the recipient.
                type: string
            required:
            - body
            - fromAddress
            - fromName
            - subject
            - toAddress
            type: object
          status:
            description: EmailStatus defines the observed state of Email.
            properties:
              errorMessage:
                type: string
              errorTimestamp:
                format: date-time
                type: string
              lastGeneration:
                format: int64
                type: integer
              sentTimestamp:
                format: date-time
                type: string
            type: object
        type: object
    selectableFields:
    - jsonPath: .spec.toAddress
    served: true
    storage: true
    subresources:
      status: {}
