---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: registrationrequests.product.webshop.harikube.info
spec:
  group: product.webshop.harikube.info
  names:
    kind: RegistrationRequest
    listKind: RegistrationRequestList
    plural: registrationrequests
    singular: registrationrequest
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: RegistrationRequest is the Schema for the registrationrequests
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: RegistrationRequestSpec defines the desired state of RegistrationRequest.
            properties:
              password:
                description: Password represents the password for the user.
                minLength: 8
                type: string
              tenant:
                description: Tenant contains the tenant information for the registration
                  request.
                properties:
                  address:
                    description: Address represents the address of the user.
                    maxLength: 512
                    minLength: 1
                    type: string
                  city:
                    description: City represents the city of the user.
                    maxLength: 50
                    minLength: 1
                    type: string
                  companyName:
                    description: CompanyName represents the company name of the user.
                    maxLength: 250
                    minLength: 1
                    type: string
                  country:
                    description: Country represents the country of the user.
                    maxLength: 3
                    minLength: 1
                    type: string
                  postalCode:
                    description: PostalCode represents the postal code of the user.
                    maxLength: 30
                    minLength: 1
                    type: string
                  taxNumber:
                    description: TaxNumber represents the tax number of the user.
                    maxLength: 256
                    minLength: 1
                    type: string
                required:
                - address
                - city
                - country
                - postalCode
                type: object
              user:
                description: User contains the user information for the registration
                  request.
                properties:
                  email:
                    description: Email represents the email address of the user.
                    format: email
                    maxLength: 256
                    minLength: 5
                    pattern: ^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$
                    type: string
                  firstName:
                    description: |-
                      FirstName represents the first name of the user.
                      Allow basic Unicode letters, spaces, apostrophes, and hyphens.
                    maxLength: 125
                    minLength: 1
                    pattern: ^[\p{L}][\p{L}\p{M}\s'\-]*$
                    type: string
                  lastName:
                    description: LastName represents the last name of the user.
                    maxLength: 125
                    minLength: 1
                    pattern: ^[\p{L}][\p{L}\p{M}\s'\-]*$
                    type: string
                  phoneNumber:
                    description: PhoneNumber represents the phone number of the user.
                    maxLength: 15
                    minLength: 7
                    pattern: ^\+?[1-9]\d{1,14}$
                    type: string
                required:
                - email
                - firstName
                - lastName
                type: object
            required:
            - password
            - tenant
            - user
            type: object
          status:
            description: RegistrationRequestStatus defines the observed state of RegistrationRequest.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
