---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: coupons.product.webshop.harikube.info
spec:
  group: product.webshop.harikube.info
  names:
    kind: Coupon
    listKind: CouponList
    plural: coupons
    singular: coupon
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      type: string
    - jsonPath: .spec.value
      name: Value
      type: integer
    - jsonPath: .spec.couponType
      name: Type
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Coupon is the Schema for the coupons API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: CouponSpec defines the desired state of Coupon.
            properties:
              couponType:
                description: CouponType represents the type of the coupon.
                enum:
                - price
                - percent
                type: string
              description:
                description: Description represents a brief description of the coupon.
                type: string
              displayName:
                description: DisplayName represents the human friendly name of the
                  coupon.
                type: string
              expireTimestamp:
                description: ExpireTimestamp represents the expiration date of the
                  coupon.
                format: date-time
                type: string
              value:
                description: value represents the value of the coupon.
                format: int64
                type: integer
            required:
            - couponType
            - displayName
            - value
            type: object
          status:
            description: CouponStatus defines the observed state of Coupon.
            properties:
              lastGeneration:
                format: int64
                type: integer
            type: object
        type: object
    selectableFields:
    - jsonPath: .spec.displayName
    - jsonPath: .spec.couponType
    served: true
    storage: true
    subresources:
      status: {}
