---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: emailtemplates.product.webshop.harikube.info
spec:
  group: product.webshop.harikube.info
  names:
    kind: EmailTemplate
    listKind: EmailTemplateList
    plural: emailtemplates
    singular: emailtemplate
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.displayName
      name: DisplayName
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: EmailTemplate is the Schema for the emailtemplates API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: EmailTemplateSpec defines the desired state of EmailTemplate.
            properties:
              body:
                description: Body represents the body content of the email.
                type: string
              description:
                description: Description represents a brief description of the template.
                type: string
              displayName:
                description: DisplayName represents the human friendly name of the
                  template.
                type: string
              fromAddress:
                description: FromAddress represents the email address of the sender.
                type: string
              fromName:
                description: FromName represents the name of the sender.
                type: string
              subject:
                description: Subject represents the subject of the email.
                type: string
            required:
            - body
            - displayName
            - fromAddress
            - fromName
            - subject
            type: object
          status:
            description: EmailTemplateStatus defines the observed state of EmailTemplate.
            properties:
              lastGeneration:
                format: int64
                type: integer
            type: object
        type: object
    selectableFields:
    - jsonPath: .spec.displayName
    served: true
    storage: true
    subresources:
      status: {}
