name: Release

on:
  push:
    branches:
    - release-v**
    - rc-v**
    - beta-v**
    - alpha-v**
    - dev-v**

concurrency: 
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}
  
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Clone the code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
          go-version-file: go.mod
    - name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Build image
      run: make docker-build
      env:
        IMG: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/example-webshop-service:${{ steps.extract_branch.outputs.branch }}
    - name: Push image
      run: make docker-push
      env:
        IMG: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/example-webshop-service:${{ steps.extract_branch.outputs.branch }}
    - name: Generate bundle
      run: make package
      env:
        IMG: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/example-webshop-service:${{ steps.extract_branch.outputs.branch }}
    - name: Create release
      if: ${{ !startsWith(github.ref, 'refs/heads/dev-') }}
      uses: mhmxs/milestone-release-action@main
      with:
        milestone-title: ${{ steps.extract_branch.outputs.branch }}
        pre-body: |
            # example-webshop-service
            This project is an example webshop service o demonstrate development simplicity with HariKube.

            ## Configuration
            For apply any configuration option please edit the Kubernetes manifests below and add extra arguments there.

            ## Configuration
            For apply any configuration option please edit the Kubernetes manifests below and add extra arguments there.

            - `--max-concurrent-reconciles`: The maximum number of concurrent Reconciles which can be run. Default: 1.

            > Requires `MutatingAdmissionPolicy` feature gate enabled.

            ## Installation
            `kubectl apply -f https://github.com/HariKube/example-webshop-service/releases/download/${{ steps.extract_branch.outputs.branch }}/bundle.yaml`

            ## Release Notes
        draft: true
        prerelease: ${{ startsWith(github.ref, 'refs/heads/rc-') || startsWith(github.ref, 'refs/heads/beta-') || startsWith(github.ref, 'refs/heads/alpha-') }}
        files: package/bundle.yaml
  